[package]
name = "reqwest-drive"
version = "0.1.0-alpha.5"
authors = ["Jeremy Harris <jeremy.harris@zenosmosis.com>"]
description = "High-performance caching, throttling, and backoff middleware for reqwest, with a single-file storage container."
repository = "https://github.com/jzombie/rust-reqwest-drive"
edition = "2021"
license = "Apache-2.0"

[dependencies]
async-trait = "0.1.88"
bincode = "1.3.3"
bytes = "1.10.1"
chrono = "0.4.40"
http = "1.3.1"
rand = "0.9.0"
reqwest = "0.12.14"
reqwest-middleware = "0.4.1"
serde = { version = "1.0.219", features = ["derive"] }
simd-r-drive = "0.3.0-alpha"
tokio = "1.44.1"

[dev-dependencies]
wiremock = "0.6.3"
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
tempdir = "0.3.7"
doc-comment = "0.3.3"
